/* This file was automatically generated by CasADi 3.6.5.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) meas_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int long long int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

static const casadi_int casadi_s0[26] = {22, 1, 0, 22, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21};
static const casadi_int casadi_s1[7] = {3, 1, 0, 3, 0, 1, 2};
static const casadi_int casadi_s2[16] = {12, 1, 0, 12, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11};
static const casadi_int casadi_s3[28] = {24, 1, 0, 24, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23};

/* meas:(i0[22],i1[3],i2[12],i3[12])->(o0[24]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1, a10, a11, a12, a13, a14, a15, a16, a17, a18, a19, a2, a20, a21, a22, a23, a24, a25, a26, a27, a28, a29, a3, a30, a31, a32, a33, a34, a35, a36, a37, a38, a39, a4, a40, a41, a42, a43, a44, a45, a46, a5, a6, a7, a8, a9;
  a0=1.8049999999999999e-01;
  a1=-2.0999999999999999e-01;
  a2=arg[2]? arg[2][1] : 0;
  a3=sin(a2);
  a4=(a1*a3);
  a4=(a0+a4);
  a5=2.0999999999999999e-01;
  a6=cos(a2);
  a7=arg[2]? arg[2][2] : 0;
  a8=sin(a7);
  a9=(a6*a8);
  a10=cos(a7);
  a11=(a3*a10);
  a9=(a9+a11);
  a9=(a5*a9);
  a4=(a4-a9);
  a9=arg[0]? arg[0][8] : 0;
  a11=cos(a9);
  a12=arg[0]? arg[0][7] : 0;
  a13=cos(a12);
  a14=(a11*a13);
  a15=arg[0]? arg[0][9] : 0;
  a16=arg[0]? arg[0][0] : 0;
  a15=(a15-a16);
  a17=(a14*a15);
  a18=sin(a9);
  a13=(a18*a13);
  a19=arg[0]? arg[0][10] : 0;
  a20=arg[0]? arg[0][1] : 0;
  a19=(a19-a20);
  a21=(a13*a19);
  a17=(a17+a21);
  a21=sin(a12);
  a22=arg[0]? arg[0][11] : 0;
  a23=arg[0]? arg[0][2] : 0;
  a22=(a22-a23);
  a24=(a21*a22);
  a17=(a17-a24);
  a17=(a4-a17);
  if (res[0]!=0) res[0][0]=a17;
  a17=4.7000000000000000e-02;
  a24=8.3799999999999999e-02;
  a25=arg[2]? arg[2][0] : 0;
  a26=cos(a25);
  a27=(a24*a26);
  a27=(a17+a27);
  a28=sin(a25);
  a29=(a28*a6);
  a30=(a1*a29);
  a27=(a27-a30);
  a30=(a28*a3);
  a30=(a30*a8);
  a29=(a29*a10);
  a30=(a30-a29);
  a30=(a5*a30);
  a27=(a27-a30);
  a30=sin(a12);
  a11=(a11*a30);
  a29=arg[0]? arg[0][6] : 0;
  a31=sin(a29);
  a32=(a11*a31);
  a33=sin(a9);
  a34=cos(a29);
  a35=(a33*a34);
  a32=(a32-a35);
  a35=(a32*a15);
  a9=cos(a9);
  a34=(a9*a34);
  a18=(a18*a30);
  a30=(a18*a31);
  a34=(a34+a30);
  a30=(a34*a19);
  a35=(a35+a30);
  a12=cos(a12);
  a31=(a12*a31);
  a30=(a31*a22);
  a35=(a35+a30);
  a35=(a27-a35);
  if (res[0]!=0) res[0][1]=a35;
  a28=(a24*a28);
  a6=(a26*a6);
  a35=(a1*a6);
  a28=(a28+a35);
  a6=(a6*a10);
  a26=(a26*a3);
  a26=(a26*a8);
  a6=(a6-a26);
  a6=(a5*a6);
  a28=(a28-a6);
  a6=sin(a29);
  a33=(a33*a6);
  a29=cos(a29);
  a11=(a11*a29);
  a33=(a33+a11);
  a15=(a33*a15);
  a18=(a18*a29);
  a9=(a9*a6);
  a18=(a18-a9);
  a19=(a18*a19);
  a15=(a15+a19);
  a12=(a12*a29);
  a22=(a12*a22);
  a15=(a15+a22);
  a15=(a28-a15);
  if (res[0]!=0) res[0][2]=a15;
  a15=arg[0]? arg[0][3] : 0;
  a22=cos(a2);
  a29=(a1*a22);
  a19=cos(a7);
  a9=(a19*a22);
  a6=sin(a7);
  a11=sin(a2);
  a26=(a6*a11);
  a9=(a9-a26);
  a9=(a5*a9);
  a29=(a29-a9);
  a9=arg[3]? arg[3][1] : 0;
  a29=(a29*a9);
  a26=cos(a2);
  a8=cos(a7);
  a3=(a26*a8);
  a2=sin(a2);
  a7=sin(a7);
  a10=(a2*a7);
  a3=(a3-a10);
  a3=(a5*a3);
  a10=arg[3]? arg[3][2] : 0;
  a3=(a3*a10);
  a29=(a29-a3);
  a3=arg[1]? arg[1][1] : 0;
  a35=(a3*a28);
  a30=arg[1]? arg[1][2] : 0;
  a36=(a30*a27);
  a35=(a35-a36);
  a29=(a29+a35);
  a35=(a14*a29);
  a36=sin(a25);
  a37=(a36*a11);
  a38=(a1*a37);
  a39=(a36*a22);
  a39=(a6*a39);
  a37=(a19*a37);
  a39=(a39+a37);
  a39=(a5*a39);
  a38=(a38-a39);
  a38=(a38*a9);
  a39=sin(a25);
  a37=(a24*a39);
  a40=cos(a25);
  a41=(a26*a40);
  a42=(a1*a41);
  a37=(a37+a42);
  a42=(a2*a40);
  a42=(a6*a42);
  a41=(a19*a41);
  a42=(a42-a41);
  a42=(a5*a42);
  a37=(a37+a42);
  a42=arg[3]? arg[3][0] : 0;
  a37=(a37*a42);
  a38=(a38-a37);
  a37=(a36*a2);
  a37=(a37*a8);
  a36=(a36*a26);
  a36=(a36*a7);
  a37=(a37+a36);
  a37=(a5*a37);
  a37=(a37*a10);
  a38=(a38-a37);
  a37=(a30*a4);
  a36=arg[1]? arg[1][0] : 0;
  a28=(a36*a28);
  a37=(a37-a28);
  a38=(a38+a37);
  a37=(a32*a38);
  a35=(a35+a37);
  a40=(a24*a40);
  a37=(a26*a39);
  a28=(a1*a37);
  a40=(a40-a28);
  a39=(a2*a39);
  a39=(a6*a39);
  a37=(a19*a37);
  a39=(a39-a37);
  a39=(a5*a39);
  a40=(a40-a39);
  a40=(a40*a42);
  a25=cos(a25);
  a11=(a25*a11);
  a19=(a19*a11);
  a22=(a25*a22);
  a6=(a6*a22);
  a19=(a19+a6);
  a19=(a5*a19);
  a11=(a1*a11);
  a19=(a19-a11);
  a19=(a19*a9);
  a40=(a40+a19);
  a26=(a25*a26);
  a26=(a26*a7);
  a25=(a25*a2);
  a25=(a25*a8);
  a26=(a26+a25);
  a26=(a5*a26);
  a26=(a26*a10);
  a40=(a40+a26);
  a27=(a36*a27);
  a4=(a3*a4);
  a27=(a27-a4);
  a40=(a40+a27);
  a27=(a33*a40);
  a35=(a35+a27);
  a35=(a15+a35);
  if (res[0]!=0) res[0][3]=a35;
  a35=arg[0]? arg[0][4] : 0;
  a27=(a13*a29);
  a4=(a34*a38);
  a27=(a27+a4);
  a4=(a18*a40);
  a27=(a27+a4);
  a27=(a35+a27);
  if (res[0]!=0) res[0][4]=a27;
  a27=arg[0]? arg[0][5] : 0;
  a38=(a31*a38);
  a29=(a21*a29);
  a38=(a38-a29);
  a40=(a12*a40);
  a38=(a38+a40);
  a38=(a27+a38);
  if (res[0]!=0) res[0][5]=a38;
  a38=arg[2]? arg[2][4] : 0;
  a40=sin(a38);
  a29=(a1*a40);
  a0=(a0+a29);
  a29=cos(a38);
  a4=arg[2]? arg[2][5] : 0;
  a26=sin(a4);
  a10=(a29*a26);
  a25=cos(a4);
  a8=(a40*a25);
  a10=(a10+a8);
  a10=(a5*a10);
  a0=(a0-a10);
  a10=arg[0]? arg[0][12] : 0;
  a10=(a10-a16);
  a8=(a14*a10);
  a2=arg[0]? arg[0][13] : 0;
  a2=(a2-a20);
  a7=(a13*a2);
  a8=(a8+a7);
  a7=arg[0]? arg[0][14] : 0;
  a7=(a7-a23);
  a19=(a21*a7);
  a8=(a8-a19);
  a8=(a0-a8);
  if (res[0]!=0) res[0][6]=a8;
  a8=-4.7000000000000000e-02;
  a19=-8.3799999999999999e-02;
  a9=arg[2]? arg[2][3] : 0;
  a11=cos(a9);
  a6=(a19*a11);
  a6=(a8+a6);
  a22=sin(a9);
  a42=(a22*a29);
  a39=(a1*a42);
  a6=(a6-a39);
  a39=(a22*a40);
  a39=(a39*a26);
  a42=(a42*a25);
  a39=(a39-a42);
  a39=(a5*a39);
  a6=(a6-a39);
  a39=(a32*a10);
  a42=(a34*a2);
  a39=(a39+a42);
  a42=(a31*a7);
  a39=(a39+a42);
  a39=(a6-a39);
  if (res[0]!=0) res[0][7]=a39;
  a22=(a19*a22);
  a29=(a11*a29);
  a39=(a1*a29);
  a22=(a22+a39);
  a29=(a29*a25);
  a11=(a11*a40);
  a11=(a11*a26);
  a29=(a29-a11);
  a29=(a5*a29);
  a22=(a22-a29);
  a10=(a33*a10);
  a2=(a18*a2);
  a10=(a10+a2);
  a7=(a12*a7);
  a10=(a10+a7);
  a10=(a22-a10);
  if (res[0]!=0) res[0][8]=a10;
  a10=cos(a38);
  a7=(a1*a10);
  a2=cos(a4);
  a29=(a2*a10);
  a11=sin(a4);
  a26=sin(a38);
  a40=(a11*a26);
  a29=(a29-a40);
  a29=(a5*a29);
  a7=(a7-a29);
  a29=arg[3]? arg[3][4] : 0;
  a7=(a7*a29);
  a40=cos(a38);
  a25=cos(a4);
  a39=(a40*a25);
  a38=sin(a38);
  a4=sin(a4);
  a42=(a38*a4);
  a39=(a39-a42);
  a39=(a5*a39);
  a42=arg[3]? arg[3][5] : 0;
  a39=(a39*a42);
  a7=(a7-a39);
  a39=(a3*a22);
  a37=(a30*a6);
  a39=(a39-a37);
  a7=(a7+a39);
  a39=(a14*a7);
  a37=sin(a9);
  a28=(a37*a26);
  a41=(a1*a28);
  a43=(a37*a10);
  a43=(a11*a43);
  a28=(a2*a28);
  a43=(a43+a28);
  a43=(a5*a43);
  a41=(a41-a43);
  a41=(a41*a29);
  a43=sin(a9);
  a28=(a19*a43);
  a44=cos(a9);
  a45=(a40*a44);
  a46=(a1*a45);
  a28=(a28+a46);
  a46=(a38*a44);
  a46=(a11*a46);
  a45=(a2*a45);
  a46=(a46-a45);
  a46=(a5*a46);
  a28=(a28+a46);
  a46=arg[3]? arg[3][3] : 0;
  a28=(a28*a46);
  a41=(a41-a28);
  a28=(a37*a38);
  a28=(a28*a25);
  a37=(a37*a40);
  a37=(a37*a4);
  a28=(a28+a37);
  a28=(a5*a28);
  a28=(a28*a42);
  a41=(a41-a28);
  a28=(a30*a0);
  a22=(a36*a22);
  a28=(a28-a22);
  a41=(a41+a28);
  a28=(a32*a41);
  a39=(a39+a28);
  a44=(a19*a44);
  a28=(a40*a43);
  a22=(a1*a28);
  a44=(a44-a22);
  a43=(a38*a43);
  a43=(a11*a43);
  a28=(a2*a28);
  a43=(a43-a28);
  a43=(a5*a43);
  a44=(a44-a43);
  a44=(a44*a46);
  a9=cos(a9);
  a26=(a9*a26);
  a2=(a2*a26);
  a10=(a9*a10);
  a11=(a11*a10);
  a2=(a2+a11);
  a2=(a5*a2);
  a26=(a1*a26);
  a2=(a2-a26);
  a2=(a2*a29);
  a44=(a44+a2);
  a40=(a9*a40);
  a40=(a40*a4);
  a9=(a9*a38);
  a9=(a9*a25);
  a40=(a40+a9);
  a40=(a5*a40);
  a40=(a40*a42);
  a44=(a44+a40);
  a6=(a36*a6);
  a0=(a3*a0);
  a6=(a6-a0);
  a44=(a44+a6);
  a6=(a33*a44);
  a39=(a39+a6);
  a39=(a15+a39);
  if (res[0]!=0) res[0][9]=a39;
  a39=(a13*a7);
  a6=(a34*a41);
  a39=(a39+a6);
  a6=(a18*a44);
  a39=(a39+a6);
  a39=(a35+a39);
  if (res[0]!=0) res[0][10]=a39;
  a41=(a31*a41);
  a7=(a21*a7);
  a41=(a41-a7);
  a44=(a12*a44);
  a41=(a41+a44);
  a41=(a27+a41);
  if (res[0]!=0) res[0][11]=a41;
  a41=-1.8049999999999999e-01;
  a44=arg[2]? arg[2][7] : 0;
  a7=sin(a44);
  a39=(a1*a7);
  a39=(a41+a39);
  a6=cos(a44);
  a0=arg[2]? arg[2][8] : 0;
  a40=sin(a0);
  a42=(a6*a40);
  a9=cos(a0);
  a25=(a7*a9);
  a42=(a42+a25);
  a42=(a5*a42);
  a39=(a39-a42);
  a42=arg[0]? arg[0][15] : 0;
  a42=(a42-a16);
  a25=(a14*a42);
  a38=arg[0]? arg[0][16] : 0;
  a38=(a38-a20);
  a4=(a13*a38);
  a25=(a25+a4);
  a4=arg[0]? arg[0][17] : 0;
  a4=(a4-a23);
  a2=(a21*a4);
  a25=(a25-a2);
  a25=(a39-a25);
  if (res[0]!=0) res[0][12]=a25;
  a25=arg[2]? arg[2][6] : 0;
  a2=cos(a25);
  a29=(a24*a2);
  a17=(a17+a29);
  a29=sin(a25);
  a26=(a29*a6);
  a11=(a1*a26);
  a17=(a17-a11);
  a11=(a29*a7);
  a11=(a11*a40);
  a26=(a26*a9);
  a11=(a11-a26);
  a11=(a5*a11);
  a17=(a17-a11);
  a11=(a32*a42);
  a26=(a34*a38);
  a11=(a11+a26);
  a26=(a31*a4);
  a11=(a11+a26);
  a11=(a17-a11);
  if (res[0]!=0) res[0][13]=a11;
  a29=(a24*a29);
  a6=(a2*a6);
  a11=(a1*a6);
  a29=(a29+a11);
  a6=(a6*a9);
  a2=(a2*a7);
  a2=(a2*a40);
  a6=(a6-a2);
  a6=(a5*a6);
  a29=(a29-a6);
  a42=(a33*a42);
  a38=(a18*a38);
  a42=(a42+a38);
  a4=(a12*a4);
  a42=(a42+a4);
  a42=(a29-a42);
  if (res[0]!=0) res[0][14]=a42;
  a42=cos(a44);
  a4=(a1*a42);
  a38=cos(a0);
  a6=(a38*a42);
  a2=sin(a0);
  a40=sin(a44);
  a7=(a2*a40);
  a6=(a6-a7);
  a6=(a5*a6);
  a4=(a4-a6);
  a6=arg[3]? arg[3][7] : 0;
  a4=(a4*a6);
  a7=cos(a44);
  a9=cos(a0);
  a11=(a7*a9);
  a44=sin(a44);
  a0=sin(a0);
  a26=(a44*a0);
  a11=(a11-a26);
  a11=(a5*a11);
  a26=arg[3]? arg[3][8] : 0;
  a11=(a11*a26);
  a4=(a4-a11);
  a11=(a3*a29);
  a10=(a30*a17);
  a11=(a11-a10);
  a4=(a4+a11);
  a11=(a14*a4);
  a10=sin(a25);
  a46=(a10*a40);
  a43=(a1*a46);
  a28=(a10*a42);
  a28=(a2*a28);
  a46=(a38*a46);
  a28=(a28+a46);
  a28=(a5*a28);
  a43=(a43-a28);
  a43=(a43*a6);
  a28=sin(a25);
  a46=(a24*a28);
  a22=cos(a25);
  a37=(a7*a22);
  a45=(a1*a37);
  a46=(a46+a45);
  a45=(a44*a22);
  a45=(a2*a45);
  a37=(a38*a37);
  a45=(a45-a37);
  a45=(a5*a45);
  a46=(a46+a45);
  a45=arg[3]? arg[3][6] : 0;
  a46=(a46*a45);
  a43=(a43-a46);
  a46=(a10*a44);
  a46=(a46*a9);
  a10=(a10*a7);
  a10=(a10*a0);
  a46=(a46+a10);
  a46=(a5*a46);
  a46=(a46*a26);
  a43=(a43-a46);
  a46=(a30*a39);
  a29=(a36*a29);
  a46=(a46-a29);
  a43=(a43+a46);
  a46=(a32*a43);
  a11=(a11+a46);
  a24=(a24*a22);
  a22=(a7*a28);
  a46=(a1*a22);
  a24=(a24-a46);
  a28=(a44*a28);
  a28=(a2*a28);
  a22=(a38*a22);
  a28=(a28-a22);
  a28=(a5*a28);
  a24=(a24-a28);
  a24=(a24*a45);
  a25=cos(a25);
  a40=(a25*a40);
  a38=(a38*a40);
  a42=(a25*a42);
  a2=(a2*a42);
  a38=(a38+a2);
  a38=(a5*a38);
  a40=(a1*a40);
  a38=(a38-a40);
  a38=(a38*a6);
  a24=(a24+a38);
  a7=(a25*a7);
  a7=(a7*a0);
  a25=(a25*a44);
  a25=(a25*a9);
  a7=(a7+a25);
  a7=(a5*a7);
  a7=(a7*a26);
  a24=(a24+a7);
  a17=(a36*a17);
  a39=(a3*a39);
  a17=(a17-a39);
  a24=(a24+a17);
  a17=(a33*a24);
  a11=(a11+a17);
  a11=(a15+a11);
  if (res[0]!=0) res[0][15]=a11;
  a11=(a13*a4);
  a17=(a34*a43);
  a11=(a11+a17);
  a17=(a18*a24);
  a11=(a11+a17);
  a11=(a35+a11);
  if (res[0]!=0) res[0][16]=a11;
  a43=(a31*a43);
  a4=(a21*a4);
  a43=(a43-a4);
  a24=(a12*a24);
  a43=(a43+a24);
  a43=(a27+a43);
  if (res[0]!=0) res[0][17]=a43;
  a43=arg[2]? arg[2][10] : 0;
  a24=sin(a43);
  a4=(a1*a24);
  a41=(a41+a4);
  a4=cos(a43);
  a11=arg[2]? arg[2][11] : 0;
  a17=sin(a11);
  a39=(a4*a17);
  a7=cos(a11);
  a26=(a24*a7);
  a39=(a39+a26);
  a39=(a5*a39);
  a41=(a41-a39);
  a39=arg[0]? arg[0][18] : 0;
  a39=(a39-a16);
  a16=(a14*a39);
  a26=arg[0]? arg[0][19] : 0;
  a26=(a26-a20);
  a20=(a13*a26);
  a16=(a16+a20);
  a20=arg[0]? arg[0][20] : 0;
  a20=(a20-a23);
  a23=(a21*a20);
  a16=(a16-a23);
  a16=(a41-a16);
  if (res[0]!=0) res[0][18]=a16;
  a16=arg[2]? arg[2][9] : 0;
  a23=cos(a16);
  a25=(a19*a23);
  a8=(a8+a25);
  a25=sin(a16);
  a9=(a25*a4);
  a44=(a1*a9);
  a8=(a8-a44);
  a44=(a25*a24);
  a44=(a44*a17);
  a9=(a9*a7);
  a44=(a44-a9);
  a44=(a5*a44);
  a8=(a8-a44);
  a44=(a32*a39);
  a9=(a34*a26);
  a44=(a44+a9);
  a9=(a31*a20);
  a44=(a44+a9);
  a44=(a8-a44);
  if (res[0]!=0) res[0][19]=a44;
  a25=(a19*a25);
  a4=(a23*a4);
  a44=(a1*a4);
  a25=(a25+a44);
  a4=(a4*a7);
  a23=(a23*a24);
  a23=(a23*a17);
  a4=(a4-a23);
  a4=(a5*a4);
  a25=(a25-a4);
  a39=(a33*a39);
  a26=(a18*a26);
  a39=(a39+a26);
  a20=(a12*a20);
  a39=(a39+a20);
  a39=(a25-a39);
  if (res[0]!=0) res[0][20]=a39;
  a39=cos(a43);
  a20=(a1*a39);
  a26=cos(a11);
  a4=(a26*a39);
  a23=sin(a11);
  a17=sin(a43);
  a24=(a23*a17);
  a4=(a4-a24);
  a4=(a5*a4);
  a20=(a20-a4);
  a4=arg[3]? arg[3][10] : 0;
  a20=(a20*a4);
  a24=cos(a43);
  a7=cos(a11);
  a44=(a24*a7);
  a43=sin(a43);
  a11=sin(a11);
  a9=(a43*a11);
  a44=(a44-a9);
  a44=(a5*a44);
  a9=arg[3]? arg[3][11] : 0;
  a44=(a44*a9);
  a20=(a20-a44);
  a44=(a3*a25);
  a0=(a30*a8);
  a44=(a44-a0);
  a20=(a20+a44);
  a14=(a14*a20);
  a44=sin(a16);
  a0=(a44*a17);
  a38=(a1*a0);
  a6=(a44*a39);
  a6=(a23*a6);
  a0=(a26*a0);
  a6=(a6+a0);
  a6=(a5*a6);
  a38=(a38-a6);
  a38=(a38*a4);
  a6=sin(a16);
  a0=(a19*a6);
  a40=cos(a16);
  a2=(a24*a40);
  a42=(a1*a2);
  a0=(a0+a42);
  a42=(a43*a40);
  a42=(a23*a42);
  a2=(a26*a2);
  a42=(a42-a2);
  a42=(a5*a42);
  a0=(a0+a42);
  a42=arg[3]? arg[3][9] : 0;
  a0=(a0*a42);
  a38=(a38-a0);
  a0=(a44*a43);
  a0=(a0*a7);
  a44=(a44*a24);
  a44=(a44*a11);
  a0=(a0+a44);
  a0=(a5*a0);
  a0=(a0*a9);
  a38=(a38-a0);
  a30=(a30*a41);
  a25=(a36*a25);
  a30=(a30-a25);
  a38=(a38+a30);
  a32=(a32*a38);
  a14=(a14+a32);
  a19=(a19*a40);
  a40=(a24*a6);
  a32=(a1*a40);
  a19=(a19-a32);
  a6=(a43*a6);
  a6=(a23*a6);
  a40=(a26*a40);
  a6=(a6-a40);
  a6=(a5*a6);
  a19=(a19-a6);
  a19=(a19*a42);
  a16=cos(a16);
  a17=(a16*a17);
  a26=(a26*a17);
  a39=(a16*a39);
  a23=(a23*a39);
  a26=(a26+a23);
  a26=(a5*a26);
  a1=(a1*a17);
  a26=(a26-a1);
  a26=(a26*a4);
  a19=(a19+a26);
  a24=(a16*a24);
  a24=(a24*a11);
  a16=(a16*a43);
  a16=(a16*a7);
  a24=(a24+a16);
  a5=(a5*a24);
  a5=(a5*a9);
  a19=(a19+a5);
  a36=(a36*a8);
  a3=(a3*a41);
  a36=(a36-a3);
  a19=(a19+a36);
  a33=(a33*a19);
  a14=(a14+a33);
  a15=(a15+a14);
  if (res[0]!=0) res[0][21]=a15;
  a13=(a13*a20);
  a34=(a34*a38);
  a13=(a13+a34);
  a18=(a18*a19);
  a13=(a13+a18);
  a35=(a35+a13);
  if (res[0]!=0) res[0][22]=a35;
  a31=(a31*a38);
  a21=(a21*a20);
  a31=(a31-a21);
  a12=(a12*a19);
  a31=(a31+a12);
  a27=(a27+a31);
  if (res[0]!=0) res[0][23]=a27;
  return 0;
}

CASADI_SYMBOL_EXPORT int meas(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int meas_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int meas_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void meas_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int meas_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void meas_release(int mem) {
}

CASADI_SYMBOL_EXPORT void meas_incref(void) {
}

CASADI_SYMBOL_EXPORT void meas_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int meas_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int meas_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real meas_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* meas_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* meas_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* meas_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    case 3: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* meas_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s3;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int meas_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 4;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

CASADI_SYMBOL_EXPORT int meas_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 4*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 1*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 0*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
