/* This file was automatically generated by CasADi 3.6.5.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) process_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int long long int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

static const casadi_int casadi_s0[26] = {22, 1, 0, 22, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21};
static const casadi_int casadi_s1[11] = {7, 1, 0, 7, 0, 1, 2, 3, 4, 5, 6};
static const casadi_int casadi_s2[5] = {1, 1, 0, 1, 0};

/* process:(i0[22],i1[7],i2[7],i3)->(o0[22]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1, a10, a11, a12, a13, a14, a15, a16, a17, a18, a19, a2, a20, a21, a22, a23, a24, a25, a26, a27, a28, a29, a3, a30, a31, a32, a33, a34, a35, a36, a37, a38, a39, a4, a40, a41, a42, a43, a44, a45, a46, a47, a48, a49, a5, a50, a51, a52, a53, a54, a55, a56, a57, a58, a59, a6, a60, a7, a8, a9;
  a0=arg[0]? arg[0][0] : 0;
  a1=1.6666666666666666e-01;
  a2=arg[3]? arg[3][0] : 0;
  a1=(a1*a2);
  a3=arg[0]? arg[0][3] : 0;
  a4=2.;
  a5=arg[0]? arg[0][8] : 0;
  a6=cos(a5);
  a7=arg[0]? arg[0][7] : 0;
  a8=cos(a7);
  a9=(a6*a8);
  a10=arg[1]? arg[1][3] : 0;
  a9=(a9*a10);
  a11=sin(a7);
  a6=(a6*a11);
  a12=arg[0]? arg[0][6] : 0;
  a13=sin(a12);
  a14=(a6*a13);
  a15=sin(a5);
  a16=cos(a12);
  a17=(a15*a16);
  a14=(a14-a17);
  a17=arg[1]? arg[1][4] : 0;
  a14=(a14*a17);
  a9=(a9+a14);
  a14=sin(a12);
  a15=(a15*a14);
  a18=cos(a12);
  a6=(a6*a18);
  a15=(a15+a6);
  a6=arg[1]? arg[1][5] : 0;
  a15=(a15*a6);
  a9=(a9+a15);
  a15=(a2*a9);
  a15=(a15/a4);
  a15=(a3+a15);
  a15=(a4*a15);
  a15=(a3+a15);
  a19=sin(a12);
  a20=cos(a7);
  a19=(a19/a20);
  a20=arg[1]? arg[1][1] : 0;
  a19=(a19*a20);
  a21=cos(a12);
  a22=cos(a7);
  a21=(a21/a22);
  a22=arg[1]? arg[1][2] : 0;
  a21=(a21*a22);
  a19=(a19+a21);
  a21=(a2*a19);
  a21=(a21/a4);
  a21=(a5+a21);
  a23=cos(a21);
  a24=cos(a12);
  a24=(a24*a20);
  a25=sin(a12);
  a25=(a25*a22);
  a24=(a24-a25);
  a25=(a2*a24);
  a25=(a25/a4);
  a25=(a7+a25);
  a26=cos(a25);
  a27=(a23*a26);
  a28=arg[2]? arg[2][3] : 0;
  a29=(a10+a28);
  a29=(a29/a4);
  a27=(a27*a29);
  a30=sin(a25);
  a23=(a23*a30);
  a31=arg[1]? arg[1][0] : 0;
  a32=sin(a7);
  a33=sin(a12);
  a32=(a32*a33);
  a33=cos(a7);
  a32=(a32/a33);
  a32=(a32*a20);
  a32=(a31+a32);
  a33=cos(a12);
  a34=sin(a7);
  a33=(a33*a34);
  a34=cos(a7);
  a33=(a33/a34);
  a33=(a33*a22);
  a32=(a32+a33);
  a33=(a2*a32);
  a33=(a33/a4);
  a33=(a12+a33);
  a34=sin(a33);
  a35=(a23*a34);
  a36=sin(a21);
  a37=cos(a33);
  a38=(a36*a37);
  a35=(a35-a38);
  a38=arg[2]? arg[2][4] : 0;
  a39=(a17+a38);
  a39=(a39/a4);
  a35=(a35*a39);
  a27=(a27+a35);
  a35=sin(a33);
  a36=(a36*a35);
  a40=cos(a33);
  a23=(a23*a40);
  a36=(a36+a23);
  a23=arg[2]? arg[2][5] : 0;
  a41=(a6+a23);
  a41=(a41/a4);
  a36=(a36*a41);
  a27=(a27+a36);
  a36=(a2*a27);
  a36=(a36/a4);
  a36=(a3+a36);
  a36=(a4*a36);
  a15=(a15+a36);
  a36=sin(a33);
  a42=cos(a25);
  a36=(a36/a42);
  a42=arg[2]? arg[2][1] : 0;
  a43=(a20+a42);
  a43=(a43/a4);
  a36=(a36*a43);
  a44=cos(a33);
  a45=cos(a25);
  a44=(a44/a45);
  a45=arg[2]? arg[2][2] : 0;
  a46=(a22+a45);
  a46=(a46/a4);
  a44=(a44*a46);
  a36=(a36+a44);
  a44=(a2*a36);
  a44=(a44/a4);
  a44=(a5+a44);
  a47=cos(a44);
  a48=cos(a33);
  a48=(a48*a43);
  a49=sin(a33);
  a49=(a49*a46);
  a48=(a48-a49);
  a49=(a2*a48);
  a49=(a49/a4);
  a49=(a7+a49);
  a50=cos(a49);
  a51=(a47*a50);
  a52=(a10+a28);
  a52=(a52/a4);
  a51=(a51*a52);
  a53=sin(a49);
  a47=(a47*a53);
  a54=arg[2]? arg[2][0] : 0;
  a55=(a31+a54);
  a55=(a55/a4);
  a56=sin(a25);
  a57=sin(a33);
  a56=(a56*a57);
  a57=cos(a25);
  a56=(a56/a57);
  a56=(a56*a43);
  a55=(a55+a56);
  a33=cos(a33);
  a56=sin(a25);
  a33=(a33*a56);
  a56=cos(a25);
  a33=(a33/a56);
  a33=(a33*a46);
  a55=(a55+a33);
  a33=(a2*a55);
  a33=(a33/a4);
  a33=(a12+a33);
  a46=sin(a33);
  a56=(a47*a46);
  a43=sin(a44);
  a57=cos(a33);
  a58=(a43*a57);
  a56=(a56-a58);
  a58=(a17+a38);
  a58=(a58/a4);
  a56=(a56*a58);
  a51=(a51+a56);
  a56=sin(a33);
  a43=(a43*a56);
  a59=cos(a33);
  a47=(a47*a59);
  a43=(a43+a47);
  a47=(a6+a23);
  a47=(a47/a4);
  a43=(a43*a47);
  a51=(a51+a43);
  a43=(a2*a51);
  a43=(a3+a43);
  a15=(a15+a43);
  a15=(a1*a15);
  a0=(a0+a15);
  if (res[0]!=0) res[0][0]=a0;
  a0=arg[0]? arg[0][1] : 0;
  a15=arg[0]? arg[0][4] : 0;
  a43=sin(a5);
  a8=(a43*a8);
  a8=(a8*a10);
  a60=cos(a5);
  a16=(a60*a16);
  a43=(a43*a11);
  a11=(a43*a13);
  a16=(a16+a11);
  a16=(a16*a17);
  a8=(a8+a16);
  a43=(a43*a18);
  a60=(a60*a14);
  a43=(a43-a60);
  a43=(a43*a6);
  a8=(a8+a43);
  a43=(a2*a8);
  a43=(a43/a4);
  a43=(a15+a43);
  a43=(a4*a43);
  a43=(a15+a43);
  a60=sin(a21);
  a26=(a60*a26);
  a26=(a26*a29);
  a21=cos(a21);
  a37=(a21*a37);
  a60=(a60*a30);
  a30=(a60*a34);
  a37=(a37+a30);
  a37=(a37*a39);
  a26=(a26+a37);
  a60=(a60*a40);
  a21=(a21*a35);
  a60=(a60-a21);
  a60=(a60*a41);
  a26=(a26+a60);
  a60=(a2*a26);
  a60=(a60/a4);
  a60=(a15+a60);
  a60=(a4*a60);
  a43=(a43+a60);
  a60=sin(a44);
  a50=(a60*a50);
  a50=(a50*a52);
  a44=cos(a44);
  a57=(a44*a57);
  a60=(a60*a53);
  a53=(a60*a46);
  a57=(a57+a53);
  a57=(a57*a58);
  a50=(a50+a57);
  a60=(a60*a59);
  a44=(a44*a56);
  a60=(a60-a44);
  a60=(a60*a47);
  a50=(a50+a60);
  a60=(a2*a50);
  a60=(a15+a60);
  a43=(a43+a60);
  a43=(a1*a43);
  a0=(a0+a43);
  if (res[0]!=0) res[0][1]=a0;
  a0=arg[0]? arg[0][2] : 0;
  a43=arg[0]? arg[0][5] : 0;
  a60=cos(a7);
  a13=(a60*a13);
  a13=(a13*a17);
  a17=sin(a7);
  a17=(a17*a10);
  a13=(a13-a17);
  a60=(a60*a18);
  a60=(a60*a6);
  a13=(a13+a60);
  a60=9.8000000000000007e+00;
  a13=(a13-a60);
  a6=(a2*a13);
  a6=(a6/a4);
  a6=(a43+a6);
  a6=(a4*a6);
  a6=(a43+a6);
  a18=cos(a25);
  a34=(a18*a34);
  a34=(a34*a39);
  a25=sin(a25);
  a25=(a25*a29);
  a34=(a34-a25);
  a18=(a18*a40);
  a18=(a18*a41);
  a34=(a34+a18);
  a34=(a34-a60);
  a18=(a2*a34);
  a18=(a18/a4);
  a18=(a43+a18);
  a18=(a4*a18);
  a6=(a6+a18);
  a18=cos(a49);
  a46=(a18*a46);
  a46=(a46*a58);
  a58=sin(a49);
  a58=(a58*a52);
  a46=(a46-a58);
  a18=(a18*a59);
  a18=(a18*a47);
  a46=(a46+a18);
  a46=(a46-a60);
  a18=(a2*a46);
  a18=(a43+a18);
  a6=(a6+a18);
  a6=(a1*a6);
  a0=(a0+a6);
  if (res[0]!=0) res[0][2]=a0;
  a27=(a4*a27);
  a9=(a9+a27);
  a51=(a4*a51);
  a9=(a9+a51);
  a51=sin(a33);
  a27=cos(a49);
  a51=(a51/a27);
  a20=(a20+a42);
  a20=(a20/a4);
  a51=(a51*a20);
  a27=cos(a33);
  a0=cos(a49);
  a27=(a27/a0);
  a22=(a22+a45);
  a22=(a22/a4);
  a27=(a27*a22);
  a51=(a51+a27);
  a27=(a2*a51);
  a27=(a5+a27);
  a0=cos(a27);
  a6=cos(a33);
  a6=(a6*a20);
  a18=sin(a33);
  a18=(a18*a22);
  a6=(a6-a18);
  a18=(a2*a6);
  a18=(a7+a18);
  a47=cos(a18);
  a59=(a0*a47);
  a59=(a59*a28);
  a58=sin(a18);
  a0=(a0*a58);
  a31=(a31+a54);
  a31=(a31/a4);
  a52=sin(a49);
  a41=sin(a33);
  a52=(a52*a41);
  a41=cos(a49);
  a52=(a52/a41);
  a52=(a52*a20);
  a31=(a31+a52);
  a33=cos(a33);
  a52=sin(a49);
  a33=(a33*a52);
  a49=cos(a49);
  a33=(a33/a49);
  a33=(a33*a22);
  a31=(a31+a33);
  a33=(a2*a31);
  a33=(a12+a33);
  a22=sin(a33);
  a49=(a0*a22);
  a52=sin(a27);
  a20=cos(a33);
  a41=(a52*a20);
  a49=(a49-a41);
  a49=(a49*a38);
  a59=(a59+a49);
  a49=sin(a33);
  a52=(a52*a49);
  a41=cos(a33);
  a0=(a0*a41);
  a52=(a52+a0);
  a52=(a52*a23);
  a59=(a59+a52);
  a9=(a9+a59);
  a9=(a1*a9);
  a3=(a3+a9);
  if (res[0]!=0) res[0][3]=a3;
  a26=(a4*a26);
  a8=(a8+a26);
  a50=(a4*a50);
  a8=(a8+a50);
  a50=sin(a27);
  a47=(a50*a47);
  a47=(a47*a28);
  a27=cos(a27);
  a20=(a27*a20);
  a50=(a50*a58);
  a58=(a50*a22);
  a20=(a20+a58);
  a20=(a20*a38);
  a47=(a47+a20);
  a50=(a50*a41);
  a27=(a27*a49);
  a50=(a50-a27);
  a50=(a50*a23);
  a47=(a47+a50);
  a8=(a8+a47);
  a8=(a1*a8);
  a15=(a15+a8);
  if (res[0]!=0) res[0][4]=a15;
  a34=(a4*a34);
  a13=(a13+a34);
  a46=(a4*a46);
  a13=(a13+a46);
  a46=cos(a18);
  a22=(a46*a22);
  a22=(a22*a38);
  a38=sin(a18);
  a38=(a38*a28);
  a22=(a22-a38);
  a46=(a46*a41);
  a46=(a46*a23);
  a22=(a22+a46);
  a22=(a22-a60);
  a13=(a13+a22);
  a13=(a1*a13);
  a43=(a43+a13);
  if (res[0]!=0) res[0][5]=a43;
  a55=(a4*a55);
  a32=(a32+a55);
  a31=(a4*a31);
  a32=(a32+a31);
  a31=sin(a18);
  a55=sin(a33);
  a31=(a31*a55);
  a55=cos(a18);
  a31=(a31/a55);
  a31=(a31*a42);
  a54=(a54+a31);
  a31=cos(a33);
  a55=sin(a18);
  a31=(a31*a55);
  a55=cos(a18);
  a31=(a31/a55);
  a31=(a31*a45);
  a54=(a54+a31);
  a32=(a32+a54);
  a32=(a1*a32);
  a12=(a12+a32);
  if (res[0]!=0) res[0][6]=a12;
  a48=(a4*a48);
  a24=(a24+a48);
  a6=(a4*a6);
  a24=(a24+a6);
  a6=cos(a33);
  a6=(a6*a42);
  a48=sin(a33);
  a48=(a48*a45);
  a6=(a6-a48);
  a24=(a24+a6);
  a24=(a1*a24);
  a7=(a7+a24);
  if (res[0]!=0) res[0][7]=a7;
  a36=(a4*a36);
  a19=(a19+a36);
  a4=(a4*a51);
  a19=(a19+a4);
  a4=sin(a33);
  a51=cos(a18);
  a4=(a4/a51);
  a4=(a4*a42);
  a33=cos(a33);
  a18=cos(a18);
  a33=(a33/a18);
  a33=(a33*a45);
  a4=(a4+a33);
  a19=(a19+a4);
  a1=(a1*a19);
  a5=(a5+a1);
  if (res[0]!=0) res[0][8]=a5;
  a5=arg[0]? arg[0][9] : 0;
  if (res[0]!=0) res[0][9]=a5;
  a5=arg[0]? arg[0][10] : 0;
  if (res[0]!=0) res[0][10]=a5;
  a5=arg[0]? arg[0][11] : 0;
  if (res[0]!=0) res[0][11]=a5;
  a5=arg[0]? arg[0][12] : 0;
  if (res[0]!=0) res[0][12]=a5;
  a5=arg[0]? arg[0][13] : 0;
  if (res[0]!=0) res[0][13]=a5;
  a5=arg[0]? arg[0][14] : 0;
  if (res[0]!=0) res[0][14]=a5;
  a5=arg[0]? arg[0][15] : 0;
  if (res[0]!=0) res[0][15]=a5;
  a5=arg[0]? arg[0][16] : 0;
  if (res[0]!=0) res[0][16]=a5;
  a5=arg[0]? arg[0][17] : 0;
  if (res[0]!=0) res[0][17]=a5;
  a5=arg[0]? arg[0][18] : 0;
  if (res[0]!=0) res[0][18]=a5;
  a5=arg[0]? arg[0][19] : 0;
  if (res[0]!=0) res[0][19]=a5;
  a5=arg[0]? arg[0][20] : 0;
  if (res[0]!=0) res[0][20]=a5;
  a5=arg[0]? arg[0][21] : 0;
  a5=(a5+a2);
  if (res[0]!=0) res[0][21]=a5;
  return 0;
}

CASADI_SYMBOL_EXPORT int process(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int process_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int process_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void process_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int process_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void process_release(int mem) {
}

CASADI_SYMBOL_EXPORT void process_incref(void) {
}

CASADI_SYMBOL_EXPORT void process_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int process_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int process_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real process_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* process_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* process_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* process_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s1;
    case 3: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* process_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int process_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 4;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

CASADI_SYMBOL_EXPORT int process_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 4*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 1*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 0*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
